version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:17.3.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cache:
          key:
            - app-{{ checksum "package.json"}}
            - app-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json"}}

  deploy-to-aws-s3:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get iinstall -y python-pip python-dev build-essential
      - run:
          name: Build project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r *.[^.]*
            echo "Build successful"
      - run:
          name: "Deploy to AWS S3"
          command: |
            if ["${CURRENT_BRANCH}" == "main"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_PRODUCTION_BUCKET} --delete
            elif ["${CURRENT_BRANCH}" == "staging"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_STAGING_BUCKET} --delete
            else
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_DEV_BUCKET} --delete
  
  deploy-to-aws-cloudfront:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get iinstall -y python-pip python-dev build-essential
      - run:
          name: Build project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r *.[^.]*
            echo "Build successful"
      - run:
          name: "Deploy to AWS Cloudfront"
          command: |
            aws configure set preview.cloudfront
            if ["${CURRENT_BRANCH}" == "main"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_PRODUCTION_BUCKET} --delete
            elif ["${CURRENT_BRANCH}" == "staging"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_STAGING_BUCKET} --delete
            else
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_DEV_BUCKET} --delete

